# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Blog CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest # 构建运行环境
    steps:
    - name: Checkout  # 获取源码，使用actions/checkout@v2
      uses: actions/checkout@v2

    - name: Install Node.js # 安装指定Node版本，使用actions/setup-node@v1
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache node modules #缓存依赖
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ./node_modules # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Dependencies
      run: yarn config set registry https://registry.npm.taobao.org | yarn install

    - name: Build
      run: yarn build


    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: "22"
          REMOTE_USER: root
          TARGET: ${{ secrets.REMOTE_TARGET }}
    
    - name: Restart Server Nginx
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.REMOTE_HOST }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}

        script: |
            nginx
            nginx -s reload